"""create requests table

Revision ID: d8e7c250588e
Revises:
Create Date: 2025-05-23 13:26:34.511235

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d8e7c250588e"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_request",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_name", sa.String(length=150), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_app_request")),
    )
    op.create_index(
        op.f("ix_app_request_id"), "app_request", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_app_request_user_name"),
        "app_request",
        ["user_name"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_app_request_user_name"), table_name="app_request")
    op.drop_index(op.f("ix_app_request_id"), table_name="app_request")
    op.drop_table("app_request")
    # ### end Alembic commands ###
